### ISSUE TITLE
博客园版本

### ISSUE THREAD

**Issue by MakerGYT** [next-theme/awesome-next#1]
# [cnblogs-theme-next](https://github.com/MakerGYT/cnblogs-theme-next)
将hexo 经典的next-theme主题迁移至博客园,使用论文格式设计，专注阅读体验,极简主义设计

## 特性
- 高度还原[next-theme](https://theme-next.js.org/)
- 响应式设计
- 支持目录、阅读进度
- 论文规范排版、衬线字体
- 与博客园既有特性融合
- 代码高亮选用github风格
- 优化评论区、上下文切换

### 截图
![](https://imgkr.cn-bj.ufileos.com/a3af8dc0-31a0-4cfb-a726-004d6fd13332.gif)
![](https://static01.imgkr.com/temp/4e9579bc084e4740873687ef112722f5.gif)

### 样例
[博客园](https://www.cnblogs.com/makergyt/p/13220468.html) <=> [hexo](https://blog.makergyt.com/)

**Comment by stevenjoezhang** [comment]
已收录至 awesome-next： https://github.com/next-theme/awesome-next#next-on-other-platforms
