### ISSUE TITLE
Cloned NexT theme into Hugo Engine(Platform).

### ISSUE THREAD

**Issue by elkan1788** [next-theme/awesome-next#10]
In the past time I were use Hexo build my blog , and become a contributiontor in NexT theme too. Now I cloned this theme into Hugo Engine think that someone cloud be like and use it .  Hope you can write down in `Awesome NexT` document, Thanks.

**Resporitory:** [https://github.com/elkan1788/hugo-theme-next](https://github.com/elkan1788/hugo-theme-next)
**LiveDemo:** [https://lisenhui.cn](https://lisenhui.cn)

**Comment by stevenjoezhang** [comment]
Repository link added to README ~ https://github.com/next-theme/awesome-next/commit/5c4b440bb5163f6c42019e280c43c86d46a0943c

**Comment by elkan1788** [comment]
@stevenjoezhang :sparkling_heart: Thanks,  and will continue to pay attention to the update of the NexT theme.
