### ISSUE TITLE
404 for hexo-filter-optimize

### ISSUE THREAD

**Issue by sosiristseng** [next-theme/awesome-next#2]
It's still on https://github.com/theme-next/hexo-filter-optimize

**Comment by stevenjoezhang** [comment]
Thanks for your feedback. This plugin is being remade and will be released later this month: https://github.com/next-theme/hexo-optimize

Docs updated: https://github.com/next-theme/awesome-next/commit/ca507c10145925d3ac315ce66e2351a0c8856ce4

Update: new version released https://www.npmjs.com/package/hexo-optimize
